{
  "formatVersion": "1.1",
  "component": {
    "group": "org.gradle.samples",
    "module": "custom-publication",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "wf6gjq6dtffkrfb2t73ax7yyke"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "custom-publication-1.0.jar",
          "url": "custom-publication-1.0.jar",
          "size": 5182,
          "sha512": "b74ca6e721c24faa0efc57153e0b35123d199b238e82a972fd284ad3153af0805dc9284f48481d6083b649cb2bd95532a74fdd476e4eb6ebca6902b603739c1e",
          "sha256": "19a699725fd3df93fe158acbf3ba94eae9bb4aff7cdc9057e7789397ba4bfcf0",
          "sha1": "d226af25ead202a4773cb7bd9062aebc09473743",
          "md5": "40f5bcfaaac72430c2e17eb4b814dd0d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "custom-publication-1.0.jar",
          "url": "custom-publication-1.0.jar",
          "size": 5182,
          "sha512": "b74ca6e721c24faa0efc57153e0b35123d199b238e82a972fd284ad3153af0805dc9284f48481d6083b649cb2bd95532a74fdd476e4eb6ebca6902b603739c1e",
          "sha256": "19a699725fd3df93fe158acbf3ba94eae9bb4aff7cdc9057e7789397ba4bfcf0",
          "sha1": "d226af25ead202a4773cb7bd9062aebc09473743",
          "md5": "40f5bcfaaac72430c2e17eb4b814dd0d"
        }
      ]
    }
  ]
}
