{
  "formatVersion": "1.1",
  "component": {
    "group": "org.gradle.samples",
    "module": "custom-publication",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "custom-publication-1.0.jar",
          "url": "custom-publication-1.0.jar",
          "size": 5182,
          "sha512": "42f0798be2ebc6656f5413ee8b3c809a71c7dec673984d35a835b8842b1480d1def6e3209696f3855c27a54f765047d221d63d6121c1b2fbd123b164933cac9e",
          "sha256": "2127743f89317a62585c869d9464ed4e6fc8919469299ad0050ad396b267773f",
          "sha1": "841f48cc7ee0904b4a28d66c99d5beff341257ee",
          "md5": "b5bbb105fb715f03fedcf33c6e4385ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "custom-publication-1.0.jar",
          "url": "custom-publication-1.0.jar",
          "size": 5182,
          "sha512": "42f0798be2ebc6656f5413ee8b3c809a71c7dec673984d35a835b8842b1480d1def6e3209696f3855c27a54f765047d221d63d6121c1b2fbd123b164933cac9e",
          "sha256": "2127743f89317a62585c869d9464ed4e6fc8919469299ad0050ad396b267773f",
          "sha1": "841f48cc7ee0904b4a28d66c99d5beff341257ee",
          "md5": "b5bbb105fb715f03fedcf33c6e4385ae"
        }
      ]
    }
  ]
}
