{
  "formatVersion": "1.1",
  "component": {
    "group": "org.gradle.samples",
    "module": "build-wrapper",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "ojyxupqbdnd2zkhxdqxviancqm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "build-wrapper-1.0.jar",
          "url": "build-wrapper-1.0.jar",
          "size": 31862,
          "sha512": "b9295d3a4efb1100d30f39ce7d3d5e56e26e08768b3268e230b248933ed4250d9ea9194d81d2ade61a5f842f96092faf058b39b10fc012f448c10b0c6a0bbcc9",
          "sha256": "27dba4d8bd098dd06b1524085f32bcd308a3fb0a7ca9cb6b851e367e974388f2",
          "sha1": "5595c0f45e4349644a6889810bdc86111821f1a7",
          "md5": "538917ba7a58f52e7ee3c4142f2c28bc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "build-wrapper-1.0.jar",
          "url": "build-wrapper-1.0.jar",
          "size": 31862,
          "sha512": "b9295d3a4efb1100d30f39ce7d3d5e56e26e08768b3268e230b248933ed4250d9ea9194d81d2ade61a5f842f96092faf058b39b10fc012f448c10b0c6a0bbcc9",
          "sha256": "27dba4d8bd098dd06b1524085f32bcd308a3fb0a7ca9cb6b851e367e974388f2",
          "sha1": "5595c0f45e4349644a6889810bdc86111821f1a7",
          "md5": "538917ba7a58f52e7ee3c4142f2c28bc"
        }
      ]
    }
  ]
}
