{
  "formatVersion": "1.1",
  "component": {
    "group": "org.gradle.samples",
    "module": "build-wrapper",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "build-wrapper-1.0.jar",
          "url": "build-wrapper-1.0.jar",
          "size": 31862,
          "sha512": "f213aadedf5096a2bf9bb7459fe99914216002491f0e9f0e4beee48bedcac1ddeaa6b8809489b8a4241daafb13cb8d2c63306f81b0961448567b7e9e3aacd483",
          "sha256": "519bb356385c06c4a693587c6b970e75a7d477b6f79b4fadb67c62cc19014e78",
          "sha1": "deda484cb4f5b692dd332e361e3260240426b099",
          "md5": "dc70e54774c5b997feb6c9b02dd92f6d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "build-wrapper-1.0.jar",
          "url": "build-wrapper-1.0.jar",
          "size": 31862,
          "sha512": "f213aadedf5096a2bf9bb7459fe99914216002491f0e9f0e4beee48bedcac1ddeaa6b8809489b8a4241daafb13cb8d2c63306f81b0961448567b7e9e3aacd483",
          "sha256": "519bb356385c06c4a693587c6b970e75a7d477b6f79b4fadb67c62cc19014e78",
          "sha1": "deda484cb4f5b692dd332e361e3260240426b099",
          "md5": "dc70e54774c5b997feb6c9b02dd92f6d"
        }
      ]
    }
  ]
}
